// Code generated by counterfeiter. DO NOT EDIT.
package pbfakes

import (
	"context"
	"sync"

	greeter "github.com/voprak/grpc-example/greeter-server/pb"
)

type FakeGreeterServer struct {
	SayHelloStub        func(context.Context, *greeter.HelloRequest) (*greeter.HelloReply, error)
	sayHelloMutex       sync.RWMutex
	sayHelloArgsForCall []struct {
		arg1 context.Context
		arg2 *greeter.HelloRequest
	}
	sayHelloReturns struct {
		result1 *greeter.HelloReply
		result2 error
	}
	sayHelloReturnsOnCall map[int]struct {
		result1 *greeter.HelloReply
		result2 error
	}
	mustEmbedUnimplementedGreeterServerStub        func()
	mustEmbedUnimplementedGreeterServerMutex       sync.RWMutex
	mustEmbedUnimplementedGreeterServerArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGreeterServer) SayHello(arg1 context.Context, arg2 *greeter.HelloRequest) (*greeter.HelloReply, error) {
	fake.sayHelloMutex.Lock()
	ret, specificReturn := fake.sayHelloReturnsOnCall[len(fake.sayHelloArgsForCall)]
	fake.sayHelloArgsForCall = append(fake.sayHelloArgsForCall, struct {
		arg1 context.Context
		arg2 *greeter.HelloRequest
	}{arg1, arg2})
	stub := fake.SayHelloStub
	fakeReturns := fake.sayHelloReturns
	fake.recordInvocation("SayHello", []interface{}{arg1, arg2})
	fake.sayHelloMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGreeterServer) SayHelloCallCount() int {
	fake.sayHelloMutex.RLock()
	defer fake.sayHelloMutex.RUnlock()
	return len(fake.sayHelloArgsForCall)
}

func (fake *FakeGreeterServer) SayHelloCalls(stub func(context.Context, *greeter.HelloRequest) (*greeter.HelloReply, error)) {
	fake.sayHelloMutex.Lock()
	defer fake.sayHelloMutex.Unlock()
	fake.SayHelloStub = stub
}

func (fake *FakeGreeterServer) SayHelloArgsForCall(i int) (context.Context, *greeter.HelloRequest) {
	fake.sayHelloMutex.RLock()
	defer fake.sayHelloMutex.RUnlock()
	argsForCall := fake.sayHelloArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGreeterServer) SayHelloReturns(result1 *greeter.HelloReply, result2 error) {
	fake.sayHelloMutex.Lock()
	defer fake.sayHelloMutex.Unlock()
	fake.SayHelloStub = nil
	fake.sayHelloReturns = struct {
		result1 *greeter.HelloReply
		result2 error
	}{result1, result2}
}

func (fake *FakeGreeterServer) SayHelloReturnsOnCall(i int, result1 *greeter.HelloReply, result2 error) {
	fake.sayHelloMutex.Lock()
	defer fake.sayHelloMutex.Unlock()
	fake.SayHelloStub = nil
	if fake.sayHelloReturnsOnCall == nil {
		fake.sayHelloReturnsOnCall = make(map[int]struct {
			result1 *greeter.HelloReply
			result2 error
		})
	}
	fake.sayHelloReturnsOnCall[i] = struct {
		result1 *greeter.HelloReply
		result2 error
	}{result1, result2}
}

func (fake *FakeGreeterServer) mustEmbedUnimplementedGreeterServer() {
	fake.mustEmbedUnimplementedGreeterServerMutex.Lock()
	fake.mustEmbedUnimplementedGreeterServerArgsForCall = append(fake.mustEmbedUnimplementedGreeterServerArgsForCall, struct {
	}{})
	stub := fake.mustEmbedUnimplementedGreeterServerStub
	fake.recordInvocation("mustEmbedUnimplementedGreeterServer", []interface{}{})
	fake.mustEmbedUnimplementedGreeterServerMutex.Unlock()
	if stub != nil {
		fake.mustEmbedUnimplementedGreeterServerStub()
	}
}

func (fake *FakeGreeterServer) MustEmbedUnimplementedGreeterServerCallCount() int {
	fake.mustEmbedUnimplementedGreeterServerMutex.RLock()
	defer fake.mustEmbedUnimplementedGreeterServerMutex.RUnlock()
	return len(fake.mustEmbedUnimplementedGreeterServerArgsForCall)
}

func (fake *FakeGreeterServer) MustEmbedUnimplementedGreeterServerCalls(stub func()) {
	fake.mustEmbedUnimplementedGreeterServerMutex.Lock()
	defer fake.mustEmbedUnimplementedGreeterServerMutex.Unlock()
	fake.mustEmbedUnimplementedGreeterServerStub = stub
}

func (fake *FakeGreeterServer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.sayHelloMutex.RLock()
	defer fake.sayHelloMutex.RUnlock()
	fake.mustEmbedUnimplementedGreeterServerMutex.RLock()
	defer fake.mustEmbedUnimplementedGreeterServerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGreeterServer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ greeter.GreeterServer = new(FakeGreeterServer)
