apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
  labels:
    app: greeter-server
spec:
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      labels:
        app: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: greeter-server-image
        ports:
        - containerPort: 9000
